services:
  - type: web
    runtime: node
    name: ivana-portfolio
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NITRO_PRESET
        value: render-com
      - key: HOST
        value: 0.0.0.0
