import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { ArrowLeft, LockKeyhole, MoonStar } from "lucide-react";
import { isSupabaseConfigured, supabase, supabaseConfigurationMessage } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/auth")({ head:()=>({meta:[{title:"Administration | Portfolio Ivana Tamno"},{name:"description",content:"Accès sécurisé à la gestion du portfolio."},{property:"og:title",content:"Administration | Portfolio Ivana Tamno"},{property:"og:description",content:"Accès sécurisé à la gestion du portfolio."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"},{name:"robots",content:"noindex, nofollow"}]}), component: AuthPage });
function AuthPage(){const navigate=useNavigate();const [mode,setMode]=useState<"login"|"signup">("login");const [error,setError]=useState("");const [busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");if(!isSupabaseConfigured){setError(supabaseConfigurationMessage);setBusy(false);return}const f=new FormData(e.currentTarget),email=String(f.get("email")),password=String(f.get("password"));if(email.toLowerCase()!=="ivanatamno@gmail.com"){setError("Cette adresse n’est pas autorisée.");setBusy(false);return}try{const result=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error){setError(result.error.message);setBusy(false);return}if(mode==="signup"&&!result.data.session){setError("Vérifiez votre boîte email pour confirmer le compte, puis connectez-vous.");setBusy(false);return}const {error:roleError}=await supabase.rpc("claim_portfolio_admin");if(roleError){setError(roleError.message);setBusy(false);return}navigate({to:"/admin"})}catch{setError("La connexion n’a pas abouti. Réessayez dans un instant.");setBusy(false)}}return <main className="auth-page"><div className="auth-panel"><Link to="/" className="back-link"><ArrowLeft/> Retour au portfolio</Link><div className="auth-mark"><MoonStar/></div><p className="eyebrow"><LockKeyhole/> Espace privé</p><h1>Administration</h1><p>Gérez les projets, documents et messages du portfolio.</p><form onSubmit={submit}><label>Adresse email<Input name="email" type="email" required defaultValue="ivanatamno@gmail.com"/></label><label>Mot de passe<Input name="password" type="password" required minLength={8}/></label>{error&&<p className="auth-error" role="alert">{error}</p>}<Button size="lg" type="submit" disabled={busy}>{busy?"Patientez…":mode==="login"?"Se connecter":"Créer mon accès"}</Button></form><button className="text-button" onClick={()=>{setMode(mode==="login"?"signup":"login");setError("")}}>{mode==="login"?"Première connexion ? Créer mon accès":"J’ai déjà un accès"}</button></div></main>}
